from .models import xroad_config
from .models import xroad_organizations
from .models import xroad_organization_id
from .models import xroad_country
from .models import xroad_service
from .models import xroad_service_id
from .models import xroad_language
from .models import xroad_postal
from .models import xroad_municipality
from .models import xroad_description
from .models import xroad_description_id
