{
    "name": "OpenG2P X-Road",
    "author": "Ishan Ranasingh",
    "version": "1.1",
    "category": "Project",
    "sequence": 12,
    "summary": "X-Road Data Exchange Layer for Openg2p",
    "depends": [],
    "description": "",
    "data": [
        "security/ir.model.access.csv",
        "views/xroad_config.xml",
        "views/xroad_organizations.xml",
        "views/xroad_service.xml",
        "views/xroad_service_by_id.xml",
        "views/xroad_organization_by_id.xml",
        "views/xroad_country.xml",
        "views/xroad_language.xml",
        "views/xroad_municipality.xml",
        "views/xroad_postal.xml",
        "views/xroad_description.xml",
        "views/xroad_description_by_id.xml",
        "views/action.xml",
        "views/menu.xml"
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
